services:
  #sets up the db
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ddc
      POSTGRES_PASSWORD: password1234
      PGDATA: /data/postgres

    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped

  #this is for self-containing app in local testing
  ddcsoftware-api:
    container_name: ddcsoftware-api
    image: ddcsoftware/ddcsoftware-api:latest
    #this overrides the URL so we connect to the db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ddc
      SPRING_DATASOURCE_USERNAME: ddc
      SPRING_DATASOURCE_PASSWORD: password1234
    ports:
      - "8080:8080"
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

#creating service for frontend done with react
  ddcsoftware-react:
    container_name: ddcsoftware-react
    image: ddcsoftware/ddcsoftware-react:latest
    build:
      #with build/context we specify where the Dockerfile is, so it knows how to build
      context: frontend/react
      #we pass the localhost port to the variable within the React Dockerfile
      args:
        api_base_url: http://localhost:8080
    #picking a random local port 3000, and 5173 as the one we chose in react
    ports:
      - "3000:5173"
    depends_on:
      - ddcsoftware-api
    restart: unless-stopped

#Network to connect all services
networks:
  postgres:
    driver: bridge

#could remove pgadmin from here. check pgadmin for info
volumes:
  postgres:
  #  pgadmin:
  #pgadmin: unnecessary for webapp now, but keeping for reference

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - postgres
#    restart: unless-stopped
#    depends_on:
#      - db


